### ISSUE TITLE
Won't compile!

### ISSUE THREAD

**Issue by 7stud** [iOSAppDevelopmentwithSwiftinAction/Bookcase#3]
The error says:  

> Module compiled with Swift 5.0.1 cannot be imported in Swift 4.0.3. 

which is next to the line:

`import SwiftyJSON`

I'm using Xcode 9.2 to follow along with the book.  The cover of the book says, 

> Covers Swift 4, Xcode 9, and iOS 11.

I'm on p. 25 of the book.  In the Bookcase project's Build Settings, I am unable to specify Swift 5.  Is there a Swift 4 version of the Bookcase project somewhere?

Okay, Swift4 version here:

https://github.com/iOSAppDevelopmentwithSwiftinAction/BookcaseSwift4

However, now I get the error:

> Module compiled with Swift 4.0 cannot be imported in Swift 4.0.3.   

which is next to the line:

`import SwiftyJSON`

Once again, I'm unable to specify Swift 4.0.3 in the Build Settings--my only choices are 3.2 and 4.0.  I guess my version of Xcode is running Swift 4.0.3:

```
~$ xcrun swift -version
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
```

Xcode 9.0.1 is available for download, so I'll try that:

https://developer.apple.com/download/more/

Before I tried Xcode 9.0.1, I deleted both the .framework files: SwiftyJSON and UIImageColors, and then I installed both of those with cocoapods.  That resulted in a try-catch error, so I wrapped a do-catch around the code:

 ```
 //Parsing with SwiftyJSON
  private func parseSwiftyJSON(data:Data, barcode:String, completionHandler: @escaping (Book?, Error?) -> Void) {

do {
    let dataAsJSON = try JSON(data: data)
    
    //loop through items (books)
    for item in dataAsJSON["items"].arrayValue {
      //loop through industry identifiers
      for id in item["volumeInfo"]["industryIdentifiers"].arrayValue {
        //check id is the ISBN we're looking for
        if id["type"].string == "ISBN_13",
          id["identifier"].string == barcode,
          let title = item["volumeInfo"]["title"].string,
          let authors = item["volumeInfo"]["authors"].array?.map({$0.string}) as? [String],
          let thumbnailURL = item["volumeInfo"]["imageLinks"]["thumbnail"].string {
          let book = Book(title: title,
                          author: authors.joined(separator: ","),
                          rating: 0, isbn: "0", notes: "")
          loadCover(book: book,
                    thumbnailURL: thumbnailURL,
                    completionHandler: completionHandler)
          return
        }
      }
    }
    completionHandler(nil, nil)
    } catch {
       //Blah
    }
  }
```
But, then I got the error:

`Shell script invocation error`

 So, I gave up.   I'll try again with Xcode 9.0.1 once it unpacks itself...

Unfortunately, I get the same shell script error with a new clone of BookcaseSwift4 and Xcode 9.0.1:

> /Users/7stud/Library/Developer/Xcode/DerivedData/Bookcase-anxdwpjfzxyojjgkqmxqscithkku/Build/Intermediates.noindex/Bookcase.build/Debug-iphonesimulator/Bookcase.build/Script-B968A4901EAE624800E6C4C0.sh: line 2: /usr/local/bin/carthage: No such file or directory

I looked at p. 425 in the book, and it looks like the book uses the Carthage package installer, and that error relates to Carthage not being installed on my computer.

I installed Carthage with:

`$ brew install carthage`

and now I can run the Bookcase app with Xcode 9.0.1.  Finally!

**Comment by iOSAppDevelopmentwithSwiftinAction** [comment]
Sorry you encountered this problem and glad you resolved it! 

I was avoiding going into Carthage in the first chapter of the book, but it meant that I had to keep on top of updating this branch with the latest compiled version of SwiftyJSON every time Swift updated and occasionally didn't get to it quickly enough!
